### ISSUE TITLE
can not to compile 

### ISSUE THREAD

**Issue by xianhuawei** [cloudflarearchive/kyototycoon#2]
g++ -c -I. -Idep/openssl/include -I/opt/kyotocabinet/include -I/usr/local/include -DNDEBUG -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D__EXTENSIONS__ -I/opt/kyotocabinet/include -D_KT_PREFIX="\"/opt/kyotocabinet\"" -D_KT_INCLUDEDIR="\"/opt/kyotocabinet/include\"" -D_KT_LIBDIR="\"/opt/kyotocabinet/lib\"" -D_KT_BINDIR="\"/opt/kyotocabinet/bin\"" -D_KT_LIBEXECDIR="\"/opt/kyotocabinet/libexec\"" -D_KT_APPINC="\"-I/opt/kyotocabinet/include\"" -D_KT_APPLIBS="\"-L/opt/kyotocabinet/lib -lkyototycoon -lkyotocabinet -lz -lstdc++ -lresolv -lnsl -lcrypto -lssl -ldl -lrt -lpthread -lm -lc \"" -march=native -m64 -g -O2 -Wall -fPIC -fsigned-char -g0 -O2 -Wno-unused-but-set-variable -Wno-unused-but-set-parameter ktremotedb.cc
In file included from ./ktcommon.h:24:0,
                 from ktremotedb.h:19,
                 from ktremotedb.cc:16:
/opt/kyotocabinet/include/kcdbext.h: In member function ‘char\* kyotocabinet::IndexDB::get(const char_, size_t, size_t_)’:
/opt/kyotocabinet/include/kcdbext.h:1281:14: warning: converting ‘false’ to pointer type ‘char_’ [-Wconversion-null]
       return false;
              ^
In file included from ktremotedb.cc:16:0:
ktremotedb.h: In member function ‘bool kyototycoon::ReplicationClient::open(const string&, int32_t, double, uint64_t, uint16_t, uint32_t)’:
ktremotedb.h:2347:25: error: call of overloaded ‘open(std::string&)’ is ambiguous
     if (!sock_.open(expr)) return false;
                         ^
ktremotedb.h:2347:25: note: candidates are:
In file included from ktremotedb.h:21:0,
                 from ktremotedb.cc:16:
./ktsocket.h:93:8: note: bool kyototycoon::Socket::open(const string&)
   bool open(const std::string& expr);
        ^
./ktsocket.h:103:8: note: bool kyototycoon::Socket::open(const string&, bool, const char_, const char_, const char_)
   bool open(const std::string& expr, bool secure = false,
        ^
make: **\* [ktremotedb.o] Error 1

**Comment by ckmaresca** [comment]
We've seen this error as well - are you all still maintaining this fork or is it abandonware?  I'm asking because there haven't been any updates in six months & this issue has been open 20 days with zero response...

**Comment by GeoffreyPlouviez** [comment]
Sorry for the late reply.
It is still maintained and it is not abandonware.
Taking a look at your issue.

**Comment by GeoffreyPlouviez** [comment]
Okay I fixed the issue. The code is available on my github and will be merged very soon.
Thanks for your patience,

**Comment by gnought** [comment]
closed at commit b18b6f949d3fb357302742d93ea70b3368833706
